apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: deployment
metadata:
  name: loadbalancer-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello 
    spec:
      containers:
        - name: hello
          image: 865955034469.dkr.ecr.us-east-2.amazonaws.com/malar-repo:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080